### ISSUE TITLE
AutoITVN

### ISSUE THREAD

**Issue by DuyMinh93** [theheroofvn/FMSF-2.0#1]
http://autoitvn.com/
Lỗi: chặn adblock...
Filter: Đã FMSF 2.0 + Nano + toàn bộ filter như hướng dẫn.
Thanks bác trước,

**Comment by nmtrung** [comment]
> http://autoitvn.com/
> Lỗi: chặn adblock...
> Filter: Đã FMSF 2.0 + Nano + toàn bộ filter như hướng dẫn.
> Thanks bác trước,

Thím xài Firefox phải ko?

**Comment by nmtrung** [comment]
@DuyMinh93 Đã fix nha thím, mời update
